import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';

export const UsageGuideModal: React.FC = () => {
  const { showUsageGuide, setShowUsageGuide, setRole, setAdminView, setShowLoginModal } = useApp();
  const [activeWorkflow, setActiveWorkflow] = useState<'admin-login' | 'admin' | 'faculty' | 'parent' | 'driver' | 'compliance'>('admin-login');

  if (!showUsageGuide) return null;

  const workflows = [
    {
      id: 'admin-login',
      label: '0. Admin Effective Login & Auth Flow',
      icon: 'lock_open',
      role: 'Super Admin, School Principal, Trust Director, Academic Dean',
      steps: [
        {
          stepNumber: '01',
          title: 'Select Institutional Campus Node (TEN-001 & IAM-001)',
          summary: 'In a multi-tenant K-12 network, Row-Level Security (RLS) requires defining tenant and branch scope. In the login screen or top bar, pick your active campus (e.g. Chennai Main Campus vs Kallakurichi Branch). The system binds the session context server-side.',
          actionLabel: 'Open Login Portal',
          action: () => { setShowLoginModal(true); setShowUsageGuide(false); },
        },
        {
          stepNumber: '02',
          title: 'Enter Admin Credentials & Pass IAM-004 MFA / 2FA Challenge',
          summary: 'Use your institutional credentials (e.g. principal@lumenacademy.edu.in). For privileged governance roles, the system immediately enforces a 6-digit TOTP code check (generated by Google Authenticator / Duo) before granting session tokens.',
          actionLabel: 'Launch Login Console',
          action: () => { setShowLoginModal(true); setShowUsageGuide(false); },
        },
        {
          stepNumber: '03',
          title: 'Verify Granular RBAC Permissions & JIT Elevation (RBAC-001–010)',
          summary: 'Admin actions are checked per verb (Read, Write, Export, Delete, Approve). For sensitive mutations like bulk student PII export or fee ledger write-offs, use the JIT Privilege Elevation toggle with reason logging in the Tenancy & RBAC view.',
          actionLabel: 'Open RBAC Governance Matrix',
          action: () => { setRole('admin'); setAdminView('auth-and-rbac'); setShowUsageGuide(false); },
        },
        {
          stepNumber: '04',
          title: 'Test Multirole Participant Experience',
          summary: 'Admins can switch instantly between Admin Command, Faculty Roster, Parent Companion, Student Academic Desk, and Bus Fleet Driver HUD using the top Portal Switcher or the Participant Persona modal to verify how other stakeholders interact with school records.',
          actionLabel: 'Switch Participant Role',
          action: () => { setShowLoginModal(true); setShowUsageGuide(false); },
        },
      ],
    },
    {
      id: 'admin',
      label: '1. School Setup & Administration',
      icon: 'admin_panel_settings',
      role: 'Super Admin, Principal, Trust Secretary',
      steps: [
        {
          stepNumber: '01',
          title: 'Establish Campus Node & Academic Session (TEN-001–009)',
          summary: 'Select your institutional campus from the top header (e.g. Chennai Main vs. Kallakurichi). Verify the active Academic Year (AY 2024–25 Term 3). Each campus enforces strict Row-Level Security (RLS) data isolation.',
          actionLabel: 'Open Tenancy & Campuses',
          action: () => { setRole('admin'); setAdminView('tenants'); setShowUsageGuide(false); },
        },
        {
          stepNumber: '02',
          title: 'Configure Masters, Board Syllabus & Grading Rules (MST-001–015)',
          summary: 'Review master records: school departments, CBSE/State board grading rules, class-section allocations, and extra-curricular clubs. This establishes the structural baseline for all downstream modules.',
          actionLabel: 'Open Masters & Configuration',
          action: () => { setRole('admin'); setAdminView('masters'); setShowUsageGuide(false); },
        },
        {
          stepNumber: '03',
          title: 'Process Admissions & Student 360 Onboarding (ADM-001–028 & STU)',
          summary: 'Admit incoming students with Aadhaar verification, automated APAAR ID generation, sibling linkage, and DPDP digital parent consent collection. Each student receives a permanent Student 360 profile.',
          actionLabel: 'Open Student 360 Profiles',
          action: () => { setRole('admin'); setAdminView('student-360'); setShowUsageGuide(false); },
        },
        {
          stepNumber: '04',
          title: 'Structure Fee Installments & Online Gateways (FEE-001–034)',
          summary: 'Assign standard tuition, lab, transport, and term fees with installment schedules. Generate real-time digital receipts, automated WhatsApp payment links, and Section 10BD tax certificates for parents.',
          actionLabel: 'Open Fees & Collections',
          action: () => { setRole('admin'); setAdminView('fees'); setShowUsageGuide(false); },
        },
      ],
    },
    {
      id: 'faculty',
      label: '2. Faculty & Classroom Operations',
      icon: 'school',
      role: 'Class Teachers, PGT/TGT Teachers, Academic HODs',
      steps: [
        {
          stepNumber: '01',
          title: 'Take Daily Roll Call with Dual Telemetry (ATT-001–026)',
          summary: 'Take period-wise or morning roll call in one tap. The system automatically reconciles manual teacher submissions with smart turnstile RFID logs and bus GPS boarding timestamps.',
          actionLabel: 'Launch Faculty Attendance Roster',
          action: () => { setRole('faculty'); setShowUsageGuide(false); },
        },
        {
          stepNumber: '02',
          title: 'Author CBSE 5E Lesson Plans / Notes of Lesson (TCH-010–015)',
          summary: 'Draft weekly unit plans using the CBSE 5E instructional framework (Engage, Explore, Explain, Elaborate, Evaluate). Track planned vs. actual syllabus variance and submit for HOD digital review.',
          actionLabel: 'Open Teacher Management (TCH)',
          action: () => { setRole('admin'); setAdminView('teacher-management'); setShowUsageGuide(false); },
        },
        {
          stepNumber: '03',
          title: 'Publish Unit Test & Term Exam Grades (EXM & TCH-024)',
          summary: 'Record formative assessment marks and scholastic grades directly into the digital gradebook with deadline compliance monitors and automated percentile rankings.',
          actionLabel: 'Open Report Cards & Grades',
          action: () => { setRole('admin'); setAdminView('report-cards'); setShowUsageGuide(false); },
        },
      ],
    },
    {
      id: 'parent',
      label: '3. Parent & Student Engagement',
      icon: 'family_restroom',
      role: 'Parents, Guardians, Students',
      steps: [
        {
          stepNumber: '01',
          title: 'Monitor Live School Bus Telematics (INT-009 & Fleet HUD)',
          summary: 'Track school bus live GPS location, current speed, geofence boundary arrivals, and RFID boarding confirmation for your child on Route #14.',
          actionLabel: 'Open Parent Companion',
          action: () => { setRole('parent'); setShowUsageGuide(false); },
        },
        {
          stepNumber: '02',
          title: 'Pay Term School Fees Online with Instant Receipts (FEE-016)',
          summary: 'View pending tuition dues and pay instantly via UPI or Net Banking. Download official CBSE fee receipts and tax clearance certificates with one click.',
          actionLabel: 'View Fee Payment Portal',
          action: () => { setRole('parent'); setShowUsageGuide(false); },
        },
        {
          stepNumber: '03',
          title: 'Exercise DPDP Child Data Consent Rights (CNS-001–015)',
          summary: 'Review and manage purpose-bound data consents (school annual magazine photos, DigiLocker sync, medical record storage) in an immutable append-only ledger.',
          actionLabel: 'Open DPDP & Consent Ledger',
          action: () => { setRole('admin'); setAdminView('dpdpa-and-consent'); setShowUsageGuide(false); },
        },
      ],
    },
    {
      id: 'driver',
      label: '4. Fleet & Campus Safety Operations',
      icon: 'directions_bus',
      role: 'Bus Drivers, Fleet Supervisors, Campus Security',
      steps: [
        {
          stepNumber: '01',
          title: 'Advance Route Stops on Mobile Fleet HUD (TRN-001–026)',
          summary: 'Follow high-contrast turn-by-turn route stops, verify student boarding counts via RFID scanner, and trigger automatic ETA alerts to waiting parents.',
          actionLabel: 'Launch Driver Console',
          action: () => { setRole('driver'); setShowUsageGuide(false); },
        },
        {
          stepNumber: '02',
          title: 'Manage Shift Rosters & Work Orders (NTS-011–020)',
          summary: 'Maintain 3-tier shift schedules (Morning, General, Night), assign maintenance work orders, and log security gate turnstile entries.',
          actionLabel: 'Open Non-Teaching Staff (NTS)',
          action: () => { setRole('admin'); setAdminView('non-teaching-staff'); setShowUsageGuide(false); },
        },
        {
          stepNumber: '03',
          title: 'Execute AIS-140 Panic SOS Protocol (INT-009)',
          summary: 'In case of breakdown or incident, trigger the AIS-140 emergency broadcast to alert the control room, principal, and parents with live telemetry.',
          actionLabel: 'Inspect Fleet HUD & SOS',
          action: () => { setRole('driver'); setShowUsageGuide(false); },
        },
      ],
    },
    {
      id: 'compliance',
      label: '5. Regulatory & Board Reporting',
      icon: 'verified',
      role: 'Compliance Officers, Auditors, CBSE Coordinators',
      steps: [
        {
          stepNumber: '01',
          title: 'Sync UDISE+ and Automated APAAR ID Registers (GOV-001–016)',
          summary: 'Export certified national database dossiers for Department of School Education compliance with zero manual data re-entry.',
          actionLabel: 'Open UDISE+ & APAAR Desk',
          action: () => { setRole('admin'); setAdminView('udise-and-apaar'); setShowUsageGuide(false); },
        },
        {
          stepNumber: '02',
          title: 'Push Verified Credentials to DigiLocker (INT-014)',
          summary: 'Direct push of high-school marksheets, bonafide certificates, and Transfer Certificates (TC) directly to student DigiLocker accounts.',
          actionLabel: 'Open DigiLocker Certificates',
          action: () => { setRole('admin'); setAdminView('certificates'); setShowUsageGuide(false); },
        },
        {
          stepNumber: '03',
          title: 'Audit System Mutations & Export Provenance (AUD-001–004)',
          summary: 'Review immutable append-only audit trails tracking every student record modification, grade update, fee concession, and bulk data export with actor IP and before/after diffs.',
          actionLabel: 'Open Append-Only Audit Logs',
          action: () => { setRole('admin'); setAdminView('audit-log'); setShowUsageGuide(false); },
        },
      ],
    },
  ];

  const currentWorkflowData = workflows.find(w => w.id === activeWorkflow) || workflows[0];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-black/60 backdrop-blur-xs animate-in fade-in">
      <div className="bg-white rounded-2xl max-w-4xl w-full max-h-[90vh] flex flex-col shadow-2xl border border-[#cbe0ec] overflow-hidden">
        {/* Modal Header */}
        <div className="bg-[#082b3d] text-white p-4 md:p-5 flex items-center justify-between border-b border-[#213145]">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-linear-to-br from-[#0e5d84] to-[#f59e0b] flex items-center justify-center text-white">
              <span className="material-symbols-outlined text-xl">menu_book</span>
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-base md:text-lg font-bold font-display text-white">
                  How to Use LumenAcademy SMS Effectively
                </h2>
                <span className="text-[10px] font-mono bg-[#0e5d84] text-[#e0f2fe] font-bold px-1.5 py-0.5 rounded">
                  OFFICIAL OPERATIONAL GUIDE
                </span>
              </div>
              <p className="text-xs text-[#bae6fd]">
                End-to-end procedural walkthrough across all 37 modules and 6 platform layers.
              </p>
            </div>
          </div>
          <button
            onClick={() => setShowUsageGuide(false)}
            className="w-8 h-8 rounded-lg bg-white/10 hover:bg-white/20 text-white flex items-center justify-center text-sm transition-colors"
          >
            ✕
          </button>
        </div>

        {/* Workflow Category Navigation */}
        <div className="bg-[#f0f7fb] border-b border-[#cbe0ec] p-2 flex items-center gap-1.5 overflow-x-auto">
          {workflows.map(wf => (
            <button
              key={wf.id}
              onClick={() => setActiveWorkflow(wf.id as any)}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap transition-all ${
                activeWorkflow === wf.id
                  ? 'bg-white text-[#0e5d84] shadow-xs'
                  : 'text-[#464555] hover:text-[#082b3d] hover:bg-white/50'
              }`}
            >
              <span className="material-symbols-outlined text-sm">{wf.icon}</span>
              <span>{wf.label}</span>
            </button>
          ))}
        </div>

        {/* Content Area */}
        <div className="flex-1 overflow-y-auto p-4 md:p-6 space-y-6">
          <div className="bg-[#f0f7fb] border border-[#0e5d84]/15 rounded-xl p-3.5 flex items-center justify-between gap-3">
            <div className="flex items-center gap-2.5">
              <span className="material-symbols-outlined text-[#0e5d84]">badge</span>
              <div>
                <div className="text-xs font-bold text-[#082b3d]">Assigned Operating Persona:</div>
                <div className="text-xs text-[#0e5d84] font-semibold">{currentWorkflowData.role}</div>
              </div>
            </div>
            <div className="text-right text-[11px] text-[#777587]">
              Step Progression: <strong className="text-[#082b3d]">{currentWorkflowData.steps.length} Key Milestones</strong>
            </div>
          </div>

          <div className="space-y-4">
            {currentWorkflowData.steps.map((s, idx) => (
              <div
                key={idx}
                className="bg-white rounded-xl border border-[#e0ecf4] p-4 hover:border-[#0e5d84]/40 transition-colors space-y-2 shadow-xs"
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="flex items-center gap-2.5">
                    <span className="w-7 h-7 rounded-lg bg-[#0e5d84] text-white text-xs font-bold font-mono flex items-center justify-center shrink-0">
                      {s.stepNumber}
                    </span>
                    <h3 className="font-bold text-sm text-[#082b3d]">{s.title}</h3>
                  </div>
                  <button
                    onClick={s.action}
                    className="inline-flex items-center gap-1 bg-[#f0f7fb] hover:bg-[#0e5d84] text-[#0e5d84] hover:text-white text-xs font-bold px-3 py-1.5 rounded-lg border border-[#cbe0ec] transition-colors shrink-0"
                  >
                    <span>{s.actionLabel}</span>
                    <span className="material-symbols-outlined text-xs">arrow_forward</span>
                  </button>
                </div>
                <p className="text-xs text-[#464555] leading-relaxed pl-9">
                  {s.summary}
                </p>
              </div>
            ))}
          </div>

          {/* Quick Best Practices Callout */}
          <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 text-xs text-[#464555] space-y-1.5">
            <div className="font-bold text-[#082b3d] flex items-center gap-1.5">
              <span className="material-symbols-outlined text-amber-600 text-sm">lightbulb</span>
              Architectural Best Practices for Optimal School Operations:
            </div>
            <ul className="list-disc list-inside space-y-1 text-[#777587] pl-1">
              <li>Always check your <strong>Campus Node</strong> in the top header before issuing bulk operations or fee structures.</li>
              <li>Use the <strong>Universal Search (⌘K)</strong> from any screen to locate students by APAAR ID, admission number, or parent mobile.</li>
              <li>Switch between <strong>Admin Console, Faculty Roster, Parent Companion, Fleet Driver HUD, and Student Academic Desk</strong> anytime using the top portal switcher or the participant login page.</li>
            </ul>
          </div>
        </div>

        {/* Modal Footer */}
        <div className="bg-white border-t border-[#e0ecf4] p-3 md:p-4 flex items-center justify-between text-xs">
          <span className="text-[#777587]">
            Full 699-feature specification mapped to LMN-SMS-FEAT-001.
          </span>
          <button
            onClick={() => setShowUsageGuide(false)}
            className="bg-[#0e5d84] hover:bg-[#083a4f] text-white font-bold px-4 py-2 rounded-xl"
          >
            Got It, Proceed to System
          </button>
        </div>
      </div>
    </div>
  );
};
