import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import {defineConfig, type Plugin} from 'vite';

// Three separately built and deployed apps. Pick one with --mode:
//   admin (default) -> index.html          -> dist/admin
//   parent          -> apps/parent/        -> dist/parent
//   teacher         -> apps/teacher/       -> dist/teacher
//   apps (dev only) -> both web apps on one origin (/parent/, /teacher/) so they share the demo store
//   demo (dev only) -> all three on one origin (/, /apps/parent/, /apps/teacher/), so work handed between the
//                      console and the web apps (e.g. unit-test paper requests) is shared in the browser
// The parent and teacher apps are installable web apps: each build also gets manifest.webmanifest and sw.js.
const APPS = {
  admin: '.',
  parent: 'apps/parent',
  teacher: 'apps/teacher',
  apps: 'apps',
  demo: '.',
} as const;
type AppName = keyof typeof APPS;

/** The admin dev server must not serve the parent or teacher apps (only their raw source, for the feature-coverage scan). */
const hideOtherApps = (): Plugin => ({
  name: 'lumen-hide-other-apps',
  configureServer(server) {
    server.middlewares.use((req, res, next) => {
      if (req.url?.startsWith('/apps/') && !/[?&]raw(&|$)/.test(req.url)) {
        res.statusCode = 404;
        res.end('Not found');
        return;
      }
      next();
    });
  },
});

/** Install details for the two web apps (PWA). */
const WEB_APPS = {
  parent: {
    name: 'Lumen Academy Parent',
    short_name: 'Lumen Parent',
    description: 'Attendance, fees, homework, results and messages for Lumen Academy parents.',
    theme_color: '#17667d',
  },
  teacher: {
    name: 'Lumen Teacher',
    short_name: 'Lumen Teacher',
    description: 'Attendance, marks, homework and parent messages for Lumen Academy teachers. Works offline.',
    theme_color: '#125569',
  },
} as const;
type WebAppName = keyof typeof WEB_APPS;

const manifestFor = (app: WebAppName, assetPrefix = '') =>
  JSON.stringify(
    {
      id: './',
      start_url: './',
      scope: './',
      display: 'standalone',
      display_override: ['window-controls-overlay', 'standalone'],
      orientation: 'any',
      background_color: '#f7f4ec',
      lang: 'en-IN',
      categories: ['education'],
      ...WEB_APPS[app],
      icons: [
        {src: `${assetPrefix}lumen-academy-logo.png`, sizes: '1037x1037', type: 'image/png', purpose: 'any'},
        {src: `${assetPrefix}lumen-academy-logo.svg`, sizes: 'any', type: 'image/svg+xml', purpose: 'any'},
      ],
    },
    null,
    2,
  );

/**
 * Offline service worker: the app shell is cached at install; pages fall back to the cached shell when the
 * network is down; built assets are served cache-first; Google Fonts are refreshed in the background.
 */
const serviceWorkerFor = (app: WebAppName, version: string, shell: string[]) => `// Generated by vite.config.ts. Do not edit.
const CACHE = 'lumen-${app}-${version}';
const SHELL = ${JSON.stringify(shell)};

self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k.startsWith('lumen-${app}-') && k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

const fromCache = request => caches.match(request, {ignoreSearch: request.mode === 'navigate'});

self.addEventListener('fetch', event => {
  const {request} = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (request.mode === 'navigate') {
    event.respondWith(fetch(request).catch(() => fromCache('./index.html').then(r => r || Response.error())));
    return;
  }
  if (url.origin === self.location.origin) {
    event.respondWith(
      fromCache(request).then(hit => hit || fetch(request).then(res => {
        if (res.ok) caches.open(CACHE).then(cache => cache.put(request, res.clone()));
        return res;
      })),
    );
    return;
  }
  if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') {
    event.respondWith(
      caches.open(CACHE).then(cache => cache.match(request).then(hit => {
        const live = fetch(request).then(res => {
          cache.put(request, res.clone());
          return res;
        });
        return hit || live;
      })),
    );
  }
});
`;

/** Adds the manifest link, serves the manifest in development and emits manifest + service worker at build. */
const webAppFiles = (only?: WebAppName): Plugin => {
  const appOf = (urlPath: string): WebAppName | undefined =>
    only ?? (Object.keys(WEB_APPS) as WebAppName[]).find(a => urlPath.startsWith(`/${a}/`) || urlPath.startsWith(`/apps/${a}/`));
  return {
    name: 'lumen-web-app-files',
    transformIndexHtml(html, ctx) {
      const app = appOf(ctx.path);
      if (!app) return html;
      return [
        {tag: 'link', attrs: {rel: 'manifest', href: './manifest.webmanifest'}, injectTo: 'head'},
        {tag: 'meta', attrs: {name: 'apple-mobile-web-app-title', content: WEB_APPS[app].short_name}, injectTo: 'head'},
        {tag: 'meta', attrs: {name: 'apple-mobile-web-app-status-bar-style', content: 'black-translucent'}, injectTo: 'head'},
      ];
    },
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const url = req.url?.split('?')[0] ?? '';
        if (!url.endsWith('/manifest.webmanifest')) return next();
        const app = appOf(url);
        if (!app) return next();
        res.setHeader('Content-Type', 'application/manifest+json');
        // In the combined dev servers the logos live at the root, above /parent/ or /apps/parent/.
        res.end(manifestFor(app, only ? '' : url.startsWith('/apps/') ? '../../' : '../'));
      });
    },
    generateBundle(_options, bundle) {
      if (!only) return;
      const files = Object.keys(bundle).filter(f => !f.endsWith('.map'));
      const shell = ['./', './index.html', './manifest.webmanifest', './lumen-academy-logo.png', './lumen-academy-logo.svg', ...files.filter(f => f !== 'index.html').map(f => `./${f}`)];
      const version = files.filter(f => f.startsWith('assets/')).sort().join('|');
      let hash = 5381;
      for (const ch of version) hash = ((hash << 5) + hash + ch.charCodeAt(0)) >>> 0;
      this.emitFile({type: 'asset', fileName: 'manifest.webmanifest', source: manifestFor(only)});
      this.emitFile({type: 'asset', fileName: 'sw.js', source: serviceWorkerFor(only, hash.toString(36), shell)});
    },
  };
};

export default defineConfig(({mode}) => {
  const app: AppName = mode in APPS ? (mode as AppName) : 'admin';
  const root = path.resolve(__dirname, APPS[app]);
  return {
    root,
    base: './',
    envDir: __dirname,
    // Each app keeps its own pre-bundle cache so running all three together doesn't thrash it.
    cacheDir: path.resolve(__dirname, 'node_modules/.vite', app),
    publicDir: path.resolve(__dirname, 'public'),
    plugins: [react(), tailwindcss(), ...(app === 'admin' ? [hideOtherApps()] : [webAppFiles(app === 'apps' || app === 'demo' ? undefined : app)])],
    // The demo server hosts the web apps itself, so the console's links point to them on the same origin.
    define:
      app === 'demo'
        ? {'import.meta.env.VITE_PARENT_APP_URL': JSON.stringify('/apps/parent/'), 'import.meta.env.VITE_TEACHER_APP_URL': JSON.stringify('/apps/teacher/')}
        : undefined,
    build: {
      outDir: path.resolve(__dirname, 'dist', app),
      emptyOutDir: true,
    },
    server: {
      fs: {allow: [__dirname]},
    },
    preview: {
      port: {admin: 4000, parent: 4001, teacher: 4002, apps: 4003, demo: 4004}[app],
    },
  };
});
